### ISSUE TITLE
laudes feria II

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#11]
ps 5, ant Framea. clef du ton : f3
MERCI Mia

Antienne elle-même : Il manque deux liquescences sur disper(h>)gunt et gre(g>)em, mais on n'en fera pas un fromage (d'autant moins que la première devrait être augmentative ;-))

Idem pour l'ant. Appenderunt ; ar(f>)gen(g>)teis
Ps. Tonus IV e : l'intonation e-fg est nettement plus élégante, et plus facile 

Ant : Inundaverunt - di(h)xi (selon CGP + neumes, pour autant que je sache)

Ant AB : Clarifica -- mundus(f) fi(d)e(cd)ret

**Comment by messige** [comment]
SVP un problème par 'Issue' : c'est plus facile à suivre et à clôturer.
Ton II-D clef du ton : f3 :  corrigé partout
Les antiennes Framea, Appenderunt sont reprises telles quelles de Giedrius. Je corrigerai pour l'an prochain.
Idem pour l'ant. Appenderunt ; ar(f>)gen(g>)teis
Ps. Tonus IV e : l'intonation e-fg est nettement plus élégante, et plus facile  : Intonation e-gh ??? fait

Ant : Inundaverunt - di(h)xi (selon CGP + neumes, pour autant que je sache) : fait

Ant AB : Clarifica -- mundus(f) fi(d)e(cd)ret : fait

**Comment by Avika1804** [comment]
> SVP un problème par 'Issue' : c'est plus facile à suivre et à clôturer.
> 
> Ton II-D clef du ton : f3 :  corrigé partout
> 
> Les antiennes Framea, Appenderunt sont reprises telles quelles de Giedrius. Je corrigerai pour l'an prochain.

De quelle version de la partition parles-tu?
J'ai comparé avec le PDF utilisé dans la partition de l'année dernière!

> 
> Idem pour l'ant. Appenderunt ; ar(f>)gen(g>)teis
> 
> Ps. Tonus IV e : l'intonation e-fg est nettement plus élégante, et plus facile  : Intonation e-gh ??? fait
> 
> 
> 
> Ant : Inundaverunt - di(h)xi (selon CGP + neumes, pour autant que je sache) : fait
> 
> 
> 
> Ant AB : Clarifica -- mundus(f) fi(d)e(cd)ret : fait
