### ISSUE TITLE
laudes feria III

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#12]
ant 3 Dum tribularer : e(g)xaudivit(f>)
ant 5 Dixerunt(f) impii
AB Ante di(dh/iv)em .... in finem(hggo>)

**Comment by messige** [comment]
ant 3 Dum tribularer : e(g)xaudivit(f>)  fait
ant 5 Dixerunt(f) impii : fait
AB Ante di(dh/iv)em .... in finem(hggo>) : vient de Giedrius (image)
