### ISSUE TITLE
feria IV ad laudes

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#13]
ANT Libera me : pas de divisio (,) après ME, mais après sanguinibus (,)(selon le sens)
ANT2 Contumelias : tamquam(hg)
ANT 3 Ipsi vero : c'est un II*. On le laisse comme ça ou on change la clef et le ton?
ANT 4 Omnes inimici : quoniam(h)

ABEN !! PLEASE :
Si(g!hwj)mon,(hvGF) dor(gh)mis?(g) (;) non(ij) po(k)tu(jh)i(jj)sti(i) (,) u(j)na(j) ho(jkj)ra(jij) vi(ji)gi(h)la(jh)re(ih) me(g)cum(g)

ORAISON 
Deus, qui pro nobis Fílium tuum crucis patíbulum subíre voluísti, ut inimíci a nobis expélleres potestátem, concéde nobis fámulis tuis, ut resurrectiónis grátiam consequámur.
Per Dóminum nostrum Iesum Christum, Fílium tuum,
qui tecum vivit et regnat in unitáte Spíritus Sancti, Deus,
per ómnia sǽcula sæculórum.

NB devrait être "Praesta" dans ton texte.

**Comment by messige** [comment]
ANT Libera me : pas de divisio (,) après ME, mais après sanguinibus (,)(selon le sens) : vient de Giedrius. J'ai le fichier gabc, il faut ajouter les neumes

ANT2 Contumelias : tamquam(hg) : il y a celeriter donc il ne faut pas chanter 'tamquaaaam' !

ANT 3 Ipsi vero  on laisse cette année

ANT 4 Omnes inimici : quoniam(h)  : fait
ORAISON : on laisse cette année

ABEN fait
