### ISSUE TITLE
Laudes feria V

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#14]
ANT 1 : Iustificeris, Domine(gf) (,) in(g) ser(h)mo(j)nibus

ANT 2 : Dominus ... ad vic(fe)ti(f)mam(g)
(devrait être : aperuit(g) pour les versions restituées l'année prochaine) ;-)

ANT contritum - o(g>)mnia

ANT exhortatus es(iio) ... re(i)fec(h)ti(g)one

Oblatus est : neumes H181
https://www.e-codices.unifr.ch/en/csg/0390/181

Traditor autem : ipse(e)

Oraison : familiam tuam (sans trait d'union) 

Merci et bonne nuit, pas la force d'aller plus loin ce soir.

**Comment by messige** [comment]
Oblatus est : neumes H181 : reporté
le reste : fait
