### ISSUE TITLE
version dite de Giedrius

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#18]
> Les antiennes Framea, Appenderunt sont reprises telles quelles de Giedrius. Je corrigerai pour l'an prochain.

De quelle version de la partition parles-tu?
J'ai comparé avec le PDF utilisé dans la partition de l'année dernière!

> 
> Idem pour l'ant. Appenderunt ; ar(f>)gen(g>)teis
> 
> Ps. Tonus IV e : l'intonation e-fg est nettement plus élégante, et plus facile  : Intonation e-gh ??? fait
> 
Je ferai un maximum de ce soir
>

**Comment by messige** [comment]
Les partitions de l'an dernier sont disponibles pour tous les participants à
https://gregorien.be/pages/index/hebsan
En cliquant sur
Ad Tertiam, ad Sextam, ad Nonam
à la page 28, on trouve l'ant. Framea 
et à la page 34 l'ant. Appenderunt
Toutes les ant. de ce fichier sont prises du Maestro Gapsys, que je ne me suis pas permis de corriger : pour l'an prochain ?

**Comment by Avika1804** [comment]
J'ai vérifié les laudes d'après les partitions des laudes.
Si ce n'est qu'une question de liquescence - peut-être une question de limites typographiques de l'époque.
Si cela concerne la mélodie c'est plus étrange et à éviter...
Le "vieux fond" CGP ne s'est pas fait sans la main de Dom Claire... 

Les partitions de l'an dernier sont disponibles pour tous les participants à
> 
> https://gregorien.be/pages/index/hebsan
> 
> En cliquant sur
> 
> Ad Tertiam, ad Sextam, ad Nonam
> 
> à la page 28, on trouve l'ant. Framea 
> 
> et à la page 34 l'ant. Appenderunt
> 
> Toutes les ant. de ce fichier sont prises du Maestro Gapsys, que je ne me suis pas permis de corriger : pour l'an prochain ?
