### ISSUE TITLE
Pâques laudes ant Prae timore autem eius

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#28]
... et(e) fac(g)ti(g) sunt(g) ve(g)lut(h) mortui, alle(gh)luia

**Comment by messige** [comment]
alle(gh)luia  ??? <> partition CGP +AM p.454  = alle(fg)luia

**Comment by Avika1804** [comment]
> alle(gh)luia  ??? <> partition CGP +AM p.454  = alle(fg)luia 

je voulais dire al(fg)le(fg)lu(e)ia(e)
