### ISSUE TITLE
Benedicamus Domino

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#33]
il n'est pas CGPien, mais pour le jour de Pâques j'ai un faible pour celui-là. Je te le dédie pour l'après lancement de l'application.
MERCI et bonne nuit

(c4) <sp>V/</sp>. Be(g)ne(e)di(f)cá(ed)mus(c.) Dó(ghGFE/gv./f/hj)mi(ivHGh)no,(i.) (;)
al(ji~)le(hvGF)lú(gf~)ia,(ede.) (,) al(gf~)le(evDCde)lú(fvED)ia.(c.) (::Z) 

<sp>R/</sp>. De(gef)o(evDC.) grá(ghGFE/gv./f/hj)ti(ivHGh)as,(i.) (;)
al(ji~)le(hvGF)lú(gf~)ia,(ede.) (,) al(gf~)le(evDCde)lú(fvED)ia.(c.) (::) 

https://gregobase.selapa.net/chant.php?id=10032

**Comment by messige** [comment]
J'essaie de produire une version CGP dans un premier temps.
