### ISSUE TITLE
Deus in adiutorium

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#7]
Sachant qu'il y a alternance entre le célébrant et celui qui fait les réponses, est-il prudent de ne noter que le début?
(mais je suis ouverte à l'expérience : disons que l'on fixe les choses pour l'année prochaine)?

**Comment by messige** [comment]
On pourrait organiser une session de présentation pour les nouveaux le samedi avant les 1ères Vêpres et expliquer ce genre de chose.
?

**Comment by messige** [comment]
Je vais créer une partition avec les tons non explicités : Deus in adiutorium, lectures, oraisons, ... : comme à la fin de l'antiphoanire

**Comment by Avika1804** [comment]
Très bonne idée!

**Comment by messige** [comment]
Ajout d'un lien vers 'Toni Communes' sur la 'home page'
