### ISSUE TITLE
vêpres feria IV

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#8]
Bonjour Gerald, 
-- le ton du psaume 134 et 135 n'est pas correct 
pour comparaison : https://www.dropbox.com/s/nim65l2zln7qrs1/feriaiv-ii.pdf?dl=0

-- ps 135, verset 13 : mare Rubrum (et non Rubrum mare)

-- le capitule : Deus MEus (pour la fin, cf. mail)

-- Magnificat, verset 9 : l'accent devrait être PUerum suum

Courage et merci

**Comment by messige** [comment]
Corrigé.
Pour le ton du psaume 134 et 135, je trouve un peu bizarre du réciter sur SI alors que l'antienne commence par sol-la-DO.
Ou bien le 3ième se chante sur DO ou bien sur SI mais pas DO pour l'antienne et SI pour la psalmodie.
Drôle de mélange des époques et des régions pour arriver à quelque chose qui n'a jamais été chanté.

**Comment by Avika1804** [comment]
Mets Do si tu veux ))
Le ton était bizarre quand même;-)

**Comment by messige** [comment]
Fixed
