### ISSUE TITLE
antiennes laudes et vêpres de Pâques

### ISSUE THREAD

**Issue by Avika1804** [messige/hebsan#9]
je ne sais pas ce qu'ils restituent à Regensburg (tu pourras peut-être m'expliquer), mais la première antienne (angelus Domini) ne correspond manifestement pas à Hartker.
Comme on avait dit que l'on gardait le vieux fond CGPien pour cette année, je préférerais m'en tenir jusqu'au bout à AM34.
Qu'en penses-tu?

**Comment by messige** [comment]
Je vais corriger, mais pour l'instant je viens de lancer une procédure de mise en place sur App Store, ce sera donc pour la version suivant.

**Comment by messige** [comment]
Fixed
